/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculadora;

import java.awt.Toolkit;
import java.util.Calendar;
import javax.swing.JOptionPane;

/**
 *
 * @author daviw
 */
public class Interface extends javax.swing.JFrame {
    int bissexto = 0, mes = 0, qtdDias = 0, diaInst = 0, diaPag = 0, intervalo = 0, validacao = 0, mesFin = 30, qtdDiasNovo = 0, qtdDiasAnt = 0, auxDataPagam = 0, diaPagAux = 0, auxDataPag1 = 0, qtdDiasNovo1 = 0;
    double valorDia = 0.0, proporcional = 0.0, valorDia1 = 0.0, valorDia2 = 0.0, valorDia3 = 0.0, valorDia4 = 0.0, valor1 = 0.0, valor2 = 0.0; 
    float resultado;
    boolean Tecnologia = true, upDown = true;
    private int ValorNovo;
    /**
     * Creates new form Interface
     */
    public Interface() {
        setResizable(false); 
        initComponents();
        setIcon();
        panResposta.setVisible(false);
        panMigrar.setVisible(false);
        panUpDown.setVisible(false);
        Calendar year = Calendar.getInstance();
        int ano = year.get(Calendar.YEAR);
        
        if(ano%4==0 && ano%100 != 0){
            bissexto = 1;
        }else if(ano%4 != 1 && ano%400 == 0){
            bissexto = 1;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        icone6 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        lbltitulo2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lbltitulo1 = new javax.swing.JLabel();
        icone1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        icone2 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        panResposta = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        lblResposta = new javax.swing.JLabel();
        btnCalc = new javax.swing.JButton();
        txtPlano = new javax.swing.JSpinner();
        txtMes = new javax.swing.JSpinner();
        txtDataInst = new javax.swing.JSpinner();
        txtDataPag = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        icone3 = new javax.swing.JLabel();
        btnMigrar = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        panMigrar = new javax.swing.JPanel();
        txtDataMud = new javax.swing.JSpinner();
        txtPlanoAnt = new javax.swing.JSpinner();
        txtPlanoNovo = new javax.swing.JSpinner();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        migraResultado = new javax.swing.JLabel();
        btnCalc1 = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        txtDataPag2 = new javax.swing.JSpinner();
        jLabel34 = new javax.swing.JLabel();
        txtMesMigra = new javax.swing.JSpinner();
        jPanel4 = new javax.swing.JPanel();
        icone4 = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        btnCalcular = new javax.swing.JButton();
        lblTroco = new javax.swing.JLabel();
        txtRecebe = new javax.swing.JSpinner();
        txtCobrar = new javax.swing.JSpinner();
        jPanel5 = new javax.swing.JPanel();
        icone5 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        panUpDown = new javax.swing.JPanel();
        txtPlan1 = new javax.swing.JSpinner();
        txtPlan2 = new javax.swing.JSpinner();
        txtDataMud1 = new javax.swing.JSpinner();
        txtDataPag1 = new javax.swing.JSpinner();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        btnCalc2 = new javax.swing.JButton();
        txtMesMud2 = new javax.swing.JSpinner();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        lblMud = new javax.swing.JLabel();
        btnUp = new javax.swing.JButton();
        btnDown = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        icone6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logo1.png"))); // NOI18N
        jPanel6.add(icone6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 100, 100));

        jLabel45.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel45.setText("RUA SALDANHA MARINHO, 56 - TÉRREO - LOJA - CAIXA D'ÁGUA - SALVADOR-BA  ");
        jPanel6.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 435, -1, -1));

        jLabel46.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel46.setText("TELEFONE FIXO ................. (71) 3233-3759 ");
        jPanel6.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 139, -1, -1));

        jLabel47.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel47.setText("WHATSAPP - Jefferson ....... (71) 99988-1538");
        jPanel6.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 279, -1, -1));

        jLabel48.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel48.setText("WHATSAPP -  Gabriel ......... (71) 98879-6079");
        jPanel6.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 244, -1, -1));

        jLabel49.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel49.setText("WHATSAPP -  Caíque ......... (71) 99319-2674");
        jPanel6.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 174, -1, -1));

        jLabel50.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel50.setText("WHATSAPP -  Luan ............ (71) 98262-8135");
        jPanel6.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 314, -1, -1));

        jLabel51.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel51.setText("WHATSAPP -  Emiliana ....... (71) 98401-7157");
        jPanel6.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 209, -1, -1));

        lbltitulo2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbltitulo2.setForeground(new java.awt.Color(0, 0, 153));
        lbltitulo2.setText("Atendnet - Contatos e Endereço");
        jPanel6.add(lbltitulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 11, -1, -1));

        jTabbedPane1.addTab("Atendent", jPanel6);

        lbltitulo1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbltitulo1.setForeground(new java.awt.Color(0, 0, 153));
        lbltitulo1.setText("Planos de Internet");

        icone1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logo1.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("Convencional - UTP");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setText("Fibra Óptica");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("1Mbps ...................... R$ 20,00 .....  R$ 0,667");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("2Mbps ...................... R$ 30,00 ...... R$ 1,00");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("3Mbps ...................... R$ 40,00 ...... R$ 1,333");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("5Mbps ...................... R$ 47,00 ...... R$ 1,567  ");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("6Mbps ...................... R$ 50,00 ...... R$ 1,667 ");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("7Mbps ...................... R$ 60,00 ...... R$ 2,00");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("10Mbps .................... R$ 75,00 ...... R$ 2,50");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("10Mbps(Premium) .... R$ 85,00 ...... R$ 2,833");

        jLabel20.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel20.setText("Plano ...................... R$ Mensal ... R$ Diário");

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setText("15Mbps .................... R$ 110,00 .... R$ 3,667  ");

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setText("Plano .......... R$ Mensal .......... R$ Diário");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("15Mbps ........ R$ 49,90 .............  R$ 1,666");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("20Mbps ........ R$ 59,90 ............. R$ 2,00");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("25Mbps ........ R$ 69,90 .............  R$ 2,333");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("30Mbps ........ R$ 74,90 .............  R$ 2,50");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("35Mbps ........ R$ 79,90 .............  R$ 2,666");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("50Mbps ........ R$ 89,90 .............  R$ 3,00");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("100Mbps ...... R$ 99,90 .............  R$ 3,333");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setText("200Mbps ...... R$ 149,90 ...........  R$ 5,00");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(125, 125, 125))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(icone1)
                        .addGap(174, 174, 174)
                        .addComponent(lbltitulo1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11))
                                .addGap(71, 71, 71)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel9))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(icone1)
                    .addComponent(lbltitulo1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel21)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Valores", jPanel1);

        icone2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logo1.png"))); // NOI18N

        jLabel22.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 153));
        jLabel22.setText("Escolha o plano para calcular o proporcional");

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel23.setText("Digite o Plano:");

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel24.setText("Mês de Instalação:");

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel25.setText("Data de Instalação:");

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel26.setText("Data de Pagamento:");

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel27.setText("Valor proporcional:");

        lblResposta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblResposta.setForeground(new java.awt.Color(51, 0, 102));
        lblResposta.setText("R$ 0,00");

        btnCalc.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCalc.setForeground(new java.awt.Color(0, 0, 51));
        btnCalc.setText("Calcular");
        btnCalc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcActionPerformed(evt);
            }
        });

        txtPlano.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPlano.setModel(new javax.swing.SpinnerNumberModel());

        txtMes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtMes.setModel(new javax.swing.SpinnerNumberModel());

        txtDataInst.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtDataInst.setModel(new javax.swing.SpinnerNumberModel());

        txtDataPag.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtDataPag.setModel(new javax.swing.SpinnerNumberModel());

        javax.swing.GroupLayout panRespostaLayout = new javax.swing.GroupLayout(panResposta);
        panResposta.setLayout(panRespostaLayout);
        panRespostaLayout.setHorizontalGroup(
            panRespostaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panRespostaLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(panRespostaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panRespostaLayout.createSequentialGroup()
                        .addGroup(panRespostaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel26)
                            .addComponent(jLabel25)
                            .addComponent(jLabel24)
                            .addComponent(jLabel23))
                        .addGap(24, 24, 24)
                        .addGroup(panRespostaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPlano, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                            .addComponent(txtDataInst)
                            .addComponent(txtDataPag)
                            .addComponent(txtMes))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panRespostaLayout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblResposta, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(panRespostaLayout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(btnCalc, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panRespostaLayout.setVerticalGroup(
            panRespostaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panRespostaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panRespostaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtPlano, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panRespostaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panRespostaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDataInst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panRespostaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDataPag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panRespostaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(lblResposta, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(btnCalc, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        jButton1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 102));
        jButton1.setText("UTP");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 102));
        jButton2.setText("Fibra");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(icone2)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(jButton1)
                        .addGap(131, 131, 131)
                        .addComponent(jButton2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panResposta, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22))))
                .addGap(0, 148, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(icone2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addGap(33, 33, 33)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(17, 17, 17)
                .addComponent(panResposta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Proporcional", jPanel2);

        icone3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logo1.png"))); // NOI18N

        btnMigrar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnMigrar.setForeground(new java.awt.Color(0, 0, 102));
        btnMigrar.setText("Clique Aqui");
        btnMigrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMigrarActionPerformed(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 0, 153));
        jLabel28.setText("Migração de Convencional para Fibra");

        txtDataMud.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtPlanoAnt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtPlanoNovo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel29.setText("Data da Mudança:");

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel30.setText("Plano Anterior:");

        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel31.setText("Novo Plano:");

        jLabel32.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel32.setText("Valor Mensalidade:");

        migraResultado.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        migraResultado.setForeground(new java.awt.Color(51, 0, 102));
        migraResultado.setText("R$ 0,00");

        btnCalc1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCalc1.setForeground(new java.awt.Color(0, 0, 51));
        btnCalc1.setText("Calcular");
        btnCalc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalc1ActionPerformed(evt);
            }
        });

        jLabel33.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel33.setText("Data de Pagamento:");

        txtDataPag2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel34.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel34.setText("Mês da Migração:");

        txtMesMigra.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout panMigrarLayout = new javax.swing.GroupLayout(panMigrar);
        panMigrar.setLayout(panMigrarLayout);
        panMigrarLayout.setHorizontalGroup(
            panMigrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panMigrarLayout.createSequentialGroup()
                .addContainerGap(76, Short.MAX_VALUE)
                .addGroup(panMigrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panMigrarLayout.createSequentialGroup()
                        .addGroup(panMigrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panMigrarLayout.createSequentialGroup()
                                .addGroup(panMigrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panMigrarLayout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addGroup(panMigrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel34)
                                            .addComponent(jLabel33)))
                                    .addComponent(jLabel31, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panMigrarLayout.createSequentialGroup()
                                .addGroup(panMigrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(10, 10, 10)))
                        .addGroup(panMigrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPlanoAnt)
                            .addComponent(txtDataMud, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                            .addComponent(txtPlanoNovo)
                            .addComponent(txtDataPag2)
                            .addComponent(txtMesMigra)))
                    .addGroup(panMigrarLayout.createSequentialGroup()
                        .addComponent(jLabel32)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(migraResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(42, 42, 42))
            .addGroup(panMigrarLayout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(btnCalc1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panMigrarLayout.setVerticalGroup(
            panMigrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panMigrarLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panMigrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMesMigra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel34))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panMigrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDataPag2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel33))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panMigrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDataMud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panMigrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPlanoAnt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panMigrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPlanoNovo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(panMigrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(migraResultado, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE))
                .addGap(15, 15, 15)
                .addComponent(btnCalc1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(icone3)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panMigrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel28)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(btnMigrar)))
                .addContainerGap(157, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnMigrar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(icone3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panMigrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Migração", jPanel3);

        icone4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logo1.png"))); // NOI18N

        lblTitulo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 0, 153));
        lblTitulo.setText("Troco para Cliente");

        jLabel35.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel35.setText("Valor Recebido:");

        jLabel36.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel36.setText("Valor a Cobrar:");

        jLabel37.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel37.setText("Troco igual a: ");

        btnCalcular.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCalcular.setForeground(new java.awt.Color(0, 0, 51));
        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        lblTroco.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTroco.setForeground(new java.awt.Color(51, 0, 102));
        lblTroco.setText("R$ 0,00");

        txtRecebe.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtRecebe.setModel(new javax.swing.SpinnerNumberModel(0.0f, null, null, 1.0f));

        txtCobrar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtCobrar.setModel(new javax.swing.SpinnerNumberModel(0.0f, null, null, 1.0f));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(icone4)
                .addGap(158, 158, 158)
                .addComponent(lblTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(280, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel35)
                            .addComponent(jLabel36))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCobrar)
                            .addComponent(txtRecebe, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(243, 243, 243))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(btnCalcular)
                        .addGap(306, 306, 306))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel37)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblTroco, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(191, 191, 191))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(icone4)
                    .addComponent(lblTitulo))
                .addGap(31, 31, 31)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(txtRecebe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(txtCobrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37)
                    .addComponent(lblTroco, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Troco", jPanel4);

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        icone5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logo1.png"))); // NOI18N
        jPanel5.add(icone5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        jLabel38.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(0, 0, 153));
        jLabel38.setText("Aumento e Diminuição de Plano");
        jPanel5.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, -1));

        txtPlan1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtPlan2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtDataMud1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtDataPag1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel39.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel39.setText("Plano Antigo:");

        jLabel40.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel40.setText("Plano Novo:");

        jLabel41.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel41.setText("Data da Mudança:");

        jLabel42.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel42.setText("Data do Pagamento:");

        btnCalc2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnCalc2.setForeground(new java.awt.Color(0, 0, 51));
        btnCalc2.setText("Calcular");
        btnCalc2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalc2ActionPerformed(evt);
            }
        });

        txtMesMud2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel43.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel43.setText("Mês de Referência:");

        jLabel44.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel44.setText("Novo Valor:");

        lblMud.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblMud.setForeground(new java.awt.Color(51, 0, 102));
        lblMud.setText("R$ 0,00");

        javax.swing.GroupLayout panUpDownLayout = new javax.swing.GroupLayout(panUpDown);
        panUpDown.setLayout(panUpDownLayout);
        panUpDownLayout.setHorizontalGroup(
            panUpDownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panUpDownLayout.createSequentialGroup()
                .addGroup(panUpDownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panUpDownLayout.createSequentialGroup()
                        .addContainerGap(71, Short.MAX_VALUE)
                        .addGroup(panUpDownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panUpDownLayout.createSequentialGroup()
                                .addComponent(jLabel40)
                                .addGap(18, 18, 18)
                                .addComponent(txtPlan2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panUpDownLayout.createSequentialGroup()
                                .addComponent(jLabel42)
                                .addGap(18, 18, 18)
                                .addComponent(txtDataPag1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panUpDownLayout.createSequentialGroup()
                                .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblMud, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panUpDownLayout.createSequentialGroup()
                                .addComponent(jLabel41)
                                .addGap(18, 18, 18)
                                .addComponent(txtDataMud1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panUpDownLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(panUpDownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panUpDownLayout.createSequentialGroup()
                                .addComponent(jLabel39)
                                .addGap(18, 18, 18)
                                .addComponent(txtPlan1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panUpDownLayout.createSequentialGroup()
                                .addComponent(jLabel43)
                                .addGap(18, 18, 18)
                                .addComponent(txtMesMud2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(117, 117, 117))
            .addGroup(panUpDownLayout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(btnCalc2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panUpDownLayout.setVerticalGroup(
            panUpDownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panUpDownLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panUpDownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMesMud2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel43))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panUpDownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDataPag1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel42))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panUpDownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDataMud1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel41))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panUpDownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPlan1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel39))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panUpDownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPlan2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel40))
                .addGap(39, 39, 39)
                .addComponent(btnCalc2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panUpDownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel44)
                    .addComponent(lblMud, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74))
        );

        jPanel5.add(panUpDown, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, -1, 320));

        btnUp.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnUp.setForeground(new java.awt.Color(0, 0, 102));
        btnUp.setText("Fibra");
        btnUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpActionPerformed(evt);
            }
        });
        jPanel5.add(btnUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 100, 50));

        btnDown.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnDown.setForeground(new java.awt.Color(0, 0, 102));
        btnDown.setText("UTP");
        btnDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDownActionPerformed(evt);
            }
        });
        jPanel5.add(btnDown, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, 100, 50));

        jTabbedPane1.addTab("Upgrade - Downgrade", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 693, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        panResposta.setVisible(true);
        Tecnologia = true;
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        panResposta.setVisible(true);
        Tecnologia = false;
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnCalcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcActionPerformed
        // TODO add your handling code here:
        
        if(Tecnologia == false){
        int plano = (int) txtPlano.getValue();// inserir fora da condicional
        switch(plano){
            case 1: 
		valorDia = 0.667;
		break;
	    case 2:
		valorDia = 1.0;
		break;
            case 3:
		valorDia = 1.333;
		break;
            case 5:
		valorDia = 1.567;
		break;		
            case 6:
		valorDia = 1.667;
		break;			
            case 7:
		valorDia = 2.0;
		break;	
            case 10:
		valorDia = 2.5;
		break;	
            case 11:
		valorDia = 2.833;
		break;	
            case 15:
		valorDia = 3.667;
		break;
            default:
                valorDia = 0.0;
                //este plano não existe, insira um valor adequado a cada plano;
            }
        }else{
            int plano = (int) txtPlano.getValue();//inserir fora da condicional
            switch(plano){
                case 15: 
                    valorDia = 1.666;
                    break;
		case 20:
                    valorDia = 2.0;
                    break;
		case 25:
                    valorDia = 2.333;
                    break;
                case 30:
                    valorDia = 2.5;
                    break;		
		case 35:
                    valorDia = 2.66;
                    break;			
		case 50:
                    valorDia = 3.0;
                    break;	
                case 100:
                    valorDia = 3.333;
                    break;	
                case 150:
                    valorDia = 5.0;
                    break;	
		case 200:
                    valorDia = 5.0;
                    break;
		default:
                    valorDia = 0.0;
            }
        }    
        
        
        mes = (int) txtMes.getValue();
        
        if(mes == 2){
            if(bissexto == 1){
                qtdDias = 29;
            }else{
                qtdDias=28;
            }
        }else if(mes == 4 || mes == 6 || mes == 9 || mes == 11){
            qtdDias = 30;
        }else if(mes == 1 || mes == 3 || mes == 5 || mes == 7 || mes == 8 || mes == 10 || mes == 12){
            qtdDias = 31;
        }else{
            proporcional = 1;   
        }
        
        diaInst = (int) txtDataInst.getValue();
        diaPag = (int) txtDataPag.getValue();
        diaPagAux = diaPag;
        if(diaInst > diaPag){
            if(diaPag < 1){
                diaPag = 0;
            }else{
                diaPag +=qtdDias;
            }
            
        }
           if(valorDia == 0){
               JOptionPane.showMessageDialog(null, "<html><center>Plano Não Existe</center>Por gentileza insira um valor de plano correto!</html>", "Mensagem Alerta!!!",JOptionPane.ERROR_MESSAGE);      
           }else if(mes < 1 || mes > 12){
               JOptionPane.showMessageDialog(null, "<html><center>Mês não Existe</center>Por gentileza insira um mês válido!</html>", "Mensagem Alerta!!!",JOptionPane.ERROR_MESSAGE);           
           }else if(diaInst > qtdDias || diaInst < 1){
                JOptionPane.showMessageDialog(null, "<html><center>Este mês contém "+ qtdDias +" dias</center>Por gentileza insira um dia de instalação válido!!!</html>", "Mensagem Alerta!!!",JOptionPane.ERROR_MESSAGE);    
           }else if(diaPag-qtdDias > qtdDias || diaPag < 1 || diaPagAux > qtdDias){
                JOptionPane.showMessageDialog(null, "<html><center>Este mês contém "+ qtdDias +" dias</center>Por gentileza insira um dia de pagamento válido!!!</html>", "Mensagem Alerta!!!",JOptionPane.ERROR_MESSAGE);
                //lblResposta.setText(" ");
           }else if((diaPag - diaInst) > 5){
                intervalo = diaPag - diaInst;
                proporcional = intervalo * valorDia;
                lblResposta.setText(String.format("R$ %.2f", proporcional));
               // String.format("%.1f", delta)
            }else{              
                //lblResposta.setText("<html>Não Paga Proporcional!!!</html>");
                JOptionPane.showMessageDialog(null, "<html><center>Não paga proporcional!!!</html>", "Mensagem de Informação!!!",JOptionPane.INFORMATION_MESSAGE);
            }
           
    }//GEN-LAST:event_btnCalcActionPerformed

    private void btnMigrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMigrarActionPerformed
        // TODO add your handling code here:
        panMigrar.setVisible(true);
    }//GEN-LAST:event_btnMigrarActionPerformed

    private void btnCalc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalc1ActionPerformed
        // TODO add your handling code here:
        panMigrar.setVisible(true);
        int dataMud = (int) txtDataMud.getValue();
        int planoAnt  = (int) txtPlanoAnt.getValue();
        switch(planoAnt){
            case 1: 
		valorDia1 = 0.667;
		break;
	    case 2:
		valorDia1 = 1.0;
		break;
            case 3:
		valorDia1 = 1.333;
		break;
            case 5:
		valorDia1 = 1.567;
		break;		
            case 6:
		valorDia1 = 1.667;
		break;			
            case 7:
		valorDia1 = 2.0;
		break;	
            case 10:
		valorDia1 = 2.5;
		break;	
            case 11:
		valorDia1 = 2.833;
		break;	
            case 15:
		valorDia1 = 3.667;
		break;  
            default:
                valorDia1 = 0.0;
                //este plano não existe, insira um valor adequado a cada plano;
            }
        int planoNovo = (int) txtPlanoNovo.getValue();    
        switch(planoNovo){
            case 15: 
                valorDia2 = 1.666;
                break;
            case 20:
                valorDia2 = 2.0;
                break;
            case 25:
                valorDia2 = 2.333;
                break;
            case 30:
                valorDia2 = 2.5;
                break;		
            case 35:
                valorDia2 = 2.66;
                break;			
            case 50:
                valorDia2 = 3.0;
                break;	
            case 100:
                valorDia2 = 3.333;
                break;	
            case 150:
                valorDia2 = 5.0;
                break;	
            case 200:
                valorDia2 = 5.0;
                break;
            default:
                valorDia2 = 0.0;
            }  
        
        int dataPagam = (int) txtDataPag2.getValue();
        mes = (int) txtMesMigra.getValue();
        if(mes == 2){
            if(bissexto == 1){
                qtdDias = 29;
            }else{
                qtdDias=28;
            }
        }else if(mes == 4 || mes == 6 || mes == 9 || mes == 11){
            qtdDias = 30;
        }else if(mes == 1 || mes == 3 || mes == 5 || mes == 7 || mes == 8 || mes == 10 || mes == 12){
            qtdDias = 31;
        }else{
            proporcional = 1;   
        }
        auxDataPagam = dataPagam;
        if(dataMud > dataPagam){
            dataPagam+=qtdDias;
        }
        qtdDiasNovo = dataPagam - dataMud;
        qtdDiasAnt = mesFin - qtdDiasNovo;
        double resultMig = qtdDiasAnt * valorDia1;
        resultMig += (qtdDiasNovo * valorDia2);
        double resultAnt = mesFin * valorDia1;
        
        if(mes < 1 || mes > 12){
            JOptionPane.showMessageDialog(null, "<html><center>Mês não Existe</center>Por gentileza insira um mês válido!</html>", "Mensagem Alerta!!!",JOptionPane.ERROR_MESSAGE);
        }else if(auxDataPagam < 1 || auxDataPagam > qtdDias){
            JOptionPane.showMessageDialog(null, "<html><center>Este mês contém "+ qtdDias +" dias</center>Por gentileza insira uma data de pagamento válido!</html>", "Mensagem Alerta!!!",JOptionPane.ERROR_MESSAGE);
        }else if(dataMud < 1 || dataMud - qtdDias > qtdDias){
            JOptionPane.showMessageDialog(null, "<html><center>Este mês contém "+ qtdDias +" dias</center>Por gentileza insira uma data de mudança válido!</html>", "Mensagem Alerta!!!",JOptionPane.ERROR_MESSAGE);
        }else if(valorDia1 == 0){
            JOptionPane.showMessageDialog(null, "<html><center>Plano antigo não existe</center>Por gentileza insira um plano antigo correto!</html>", "Mensagem Alerta!!!",JOptionPane.ERROR_MESSAGE);
        }else if(valorDia2 == 0){
            JOptionPane.showMessageDialog(null, "<html><center>Plano novo não Existe</center>Por gentileza insira um plano novo correto!</html>", "Mensagem Alerta!!!",JOptionPane.ERROR_MESSAGE);
        }else if(qtdDiasNovo <= 10){
            migraResultado.setText("R$"+resultAnt);
            JOptionPane.showMessageDialog(null, "<html><center>Não Altera o valor da cobrança!</html>", "Mensagem de Informação!!!",JOptionPane.INFORMATION_MESSAGE);
        }else{
            migraResultado.setText(String.format("R$ %.2f", resultMig));
        }
        
        //lblResposta.setText(String.format("R$ %.2f", proporcional));
        
        
        
    }//GEN-LAST:event_btnCalc1ActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        // TODO add your handling code here:
        //int a = Integer.parseInt(txtA.getValue().toString());
        float recebeDinheiro = Float.parseFloat(txtRecebe.getValue().toString());
        float valorCobrado = Float.parseFloat(txtCobrar.getValue().toString());
        resultado = recebeDinheiro - valorCobrado;
        
        lblTroco.setText(String.format("R$ %.2f", resultado));
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void btnDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDownActionPerformed
        // TODO add your handling code here:
        panUpDown.setVisible(true);
        upDown = false;    
    }//GEN-LAST:event_btnDownActionPerformed

    private void btnUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpActionPerformed
        // TODO add your handling code here:
        panUpDown.setVisible(true);
        upDown = true;
    }//GEN-LAST:event_btnUpActionPerformed

    private void btnCalc2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalc2ActionPerformed
        // TODO add your handling code here:
        
        if(upDown == true){           
            int planoAnt1 = (int) txtPlan1.getValue();         
            switch(planoAnt1){
            case 15: 
                valorDia3 = 1.666;
                break;
            case 20:
                valorDia3 = 2.0;
                break;
            case 25:
                valorDia3 = 2.333;
                break;
            case 30:
                valorDia3 = 2.5;
                break;		
            case 35:
                valorDia3 = 2.66;
                break;			
            case 50:
                valorDia3 = 3.0;
                break;	
            case 100:
                valorDia3 = 3.333;
                break;	
            case 150:
                valorDia3 = 5.0;
                break;	
            case 200:
                valorDia3 = 5.0;
                break;
            default:
                valorDia3 = 0.0;
            }
            int planAnt2 = (int) txtPlan2.getValue(); 
            switch(planAnt2){
            case 15: 
                valorDia4 = 1.666;
                break;
            case 20:
                valorDia4 = 2.0;
                break;
            case 25:
                valorDia4 = 2.333;
                break;
            case 30:
                valorDia4 = 2.5;
                break;		
            case 35:
                valorDia4 = 2.66;
                break;			
            case 50:
                valorDia4 = 3.0;
                break;	
            case 100:
                valorDia4 = 3.333;
                break;	
            case 150:
                valorDia4 = 5.0;
                break;	
            case 200:
                valorDia4 = 5.0;
                break;
            default:
                valorDia4 = 0.0;
            }  
        }else{
            int planoAnt1 = (int) txtPlan1.getValue();         
            switch(planoAnt1){
            case 1: 
		valorDia3 = 0.667;
		break;
	    case 2:
		valorDia3 = 1.0;
		break;
            case 3:
		valorDia3 = 1.333;
		break;
            case 5:
		valorDia3 = 1.567;
		break;		
            case 6:
		valorDia3 = 1.667;
		break;			
            case 7:
		valorDia3 = 2.0;
		break;	
            case 10:
		valorDia3 = 2.5;
		break;	
            case 11:
		valorDia3 = 2.833;
		break;	
            case 15:
		valorDia3 = 3.667;
		break;  
            default:
                valorDia3 = 0.0;
            }
            int planAnt2 = (int) txtPlan2.getValue(); 
            switch(planAnt2){
            case 1: 
		valorDia4 = 0.667;
		break;
	    case 2:
		valorDia4 = 1.0;
		break;
            case 3:
		valorDia4 = 1.333;
		break;
            case 5:
		valorDia4 = 1.567;
		break;		
            case 6:
		valorDia4 = 1.667;
		break;			
            case 7:
		valorDia4 = 2.0;
		break;	
            case 10:
		valorDia4 = 2.5;
		break;	
            case 11:
		valorDia4 = 2.833;
		break;	
            case 15:
		valorDia4 = 3.667;
		break;  
            default:
                valorDia4 = 0.0;
            }
        }
        
        mes = (int) txtMesMud2.getValue();
        if(mes == 2){
            if(bissexto == 1){
                qtdDias = 29;
            }else{
                qtdDias=28;
            }
        }else if(mes == 4 || mes == 6 || mes == 9 || mes == 11){
            qtdDias = 30;
        }else if(mes == 1 || mes == 3 || mes == 5 || mes == 7 || mes == 8 || mes == 10 || mes == 12){
            qtdDias = 31;
        }
        
        int dataPag1 = (int) txtDataPag1.getValue();
        int dataMud1 = (int) txtDataMud1.getValue();
        
        auxDataPag1 = dataPag1;
        if(dataMud1 > dataPag1){
            dataMud1-=dataPag1;
            dataPag1 = qtdDias - dataMud1;
            //valor1 = dataMud1 * valorDia3;
            valor2 = dataPag1 * valorDia4;
            valor1 = 0;
        }else{
            //valor1 = dataMud1 * valorDia3;
            valor1 = (qtdDias - dataPag1) * valorDia3;
            valor2 = ((dataPag1+1) - dataMud1) * valorDia4;
        }  
        qtdDiasNovo1 = auxDataPag1 - dataMud1;
        double resultadoMud = valor1 + valor2;
        if(mes < 1 || mes > 12){
            JOptionPane.showMessageDialog(null, "<html><center>Mês não Existe</center>Por gentileza insira um mês válido!</html>", "Mensagem Alerta!!!",JOptionPane.ERROR_MESSAGE);
        }else if(auxDataPag1 < 1 || auxDataPag1 > qtdDias){
            JOptionPane.showMessageDialog(null, "<html><center>Este mês contém "+ qtdDias +" dias</center>Por gentileza insira uma data de pagamento válido!</html>", "Mensagem Alerta!!!",JOptionPane.ERROR_MESSAGE);
        }else if(dataMud1 < 1 || dataMud1 - qtdDias > qtdDias){
            JOptionPane.showMessageDialog(null, "<html><center>Este mês contém "+ qtdDias +" dias</center>Por gentileza insira uma data de mudança válido!</html>", "Mensagem Alerta!!!",JOptionPane.ERROR_MESSAGE);
        }else if(valorDia3 == 0){
            JOptionPane.showMessageDialog(null, "<html><center>Plano antigo não existe</center>Por gentileza insira um plano antigo correto!</html>", "Mensagem Alerta!!!",JOptionPane.ERROR_MESSAGE);
        }else if(valorDia4 == 0){
            JOptionPane.showMessageDialog(null, "<html><center>Plano novo não Existe</center>Por gentileza insira um plano novo correto!</html>", "Mensagem Alerta!!!",JOptionPane.ERROR_MESSAGE);
        }else if(qtdDiasNovo1 <= 5){
            JOptionPane.showMessageDialog(null, "<html><center>Não Altera o valor da cobrança!</html>", "Mensagem de Informação!!!",JOptionPane.INFORMATION_MESSAGE);
        }else{
            lblMud.setText(String.format("R$ %.2f", resultadoMud));
        }       
        
    }//GEN-LAST:event_btnCalc2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("calc1.png")));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalc;
    private javax.swing.JButton btnCalc1;
    private javax.swing.JButton btnCalc2;
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnDown;
    private javax.swing.JButton btnMigrar;
    private javax.swing.JButton btnUp;
    private javax.swing.JLabel icone1;
    private javax.swing.JLabel icone2;
    private javax.swing.JLabel icone3;
    private javax.swing.JLabel icone4;
    private javax.swing.JLabel icone5;
    private javax.swing.JLabel icone6;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblMud;
    private javax.swing.JLabel lblResposta;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTroco;
    private javax.swing.JLabel lbltitulo1;
    private javax.swing.JLabel lbltitulo2;
    private javax.swing.JLabel migraResultado;
    private javax.swing.JPanel panMigrar;
    private javax.swing.JPanel panResposta;
    private javax.swing.JPanel panUpDown;
    private javax.swing.JSpinner txtCobrar;
    private javax.swing.JSpinner txtDataInst;
    private javax.swing.JSpinner txtDataMud;
    private javax.swing.JSpinner txtDataMud1;
    private javax.swing.JSpinner txtDataPag;
    private javax.swing.JSpinner txtDataPag1;
    private javax.swing.JSpinner txtDataPag2;
    private javax.swing.JSpinner txtMes;
    private javax.swing.JSpinner txtMesMigra;
    private javax.swing.JSpinner txtMesMud2;
    private javax.swing.JSpinner txtPlan1;
    private javax.swing.JSpinner txtPlan2;
    private javax.swing.JSpinner txtPlano;
    private javax.swing.JSpinner txtPlanoAnt;
    private javax.swing.JSpinner txtPlanoNovo;
    private javax.swing.JSpinner txtRecebe;
    // End of variables declaration//GEN-END:variables
}
